sudo: required
dist: trusty
language: node_js
node_js:
- 6.9.1
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - google-chrome
    packages:
    - g++-4.8
    - google-chrome-stable
cache:
  directories:
  - node_modules
branches:
  except:
  - "/^v[0-9\\.]+/"
before_install:
- npm install -g pr-bumper
- pr-bumper check
- cp .env.example .env
- sudo apt-get update
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
install:
- travis_retry npm install
script:
- npm test
- npm run build
after_success:
- npm run coveralls
before_deploy:
- eval "$(ssh-agent -s)"
- openssl aes-256-cbc -K $encrypted_953c8d6bcb38_key -iv $encrypted_953c8d6bcb38_iv
  -in .travis/deployment.key.pem.enc -out .travis/deployment.key.pem -d
- chmod 600 .travis/deployment.key.pem
- ssh-add .travis/deployment.key.pem
- pr-bumper bump
- git fetch --tags
- npm run preparepublish
env:
  global:
  - secure: Ht4a2ay7PKrzH8A2WVnP6+foA+BZ7jUkK6Q3/GP0fHmxkvt7NT7Q2FN8yXGFQOk6qd6PIewbcUmhj0CG74AEyDb6F0qyKUZvv6f1YvMSDd+S0BYkPt3CkPdkpxVSaOQSPk84+JnDGXrB8roDviuw6zuqSIM6iKPCgAcLFyB1fxG0RUjpdA4MiNgL/e4IT8tncF4kR3z83etHQfgECF5CUF4rNXL0LDIIVeslW6mVzggKfao/0TvJsMsau60Cmk/CC46Vs8SUp1UwAFsRuazU/sNgGJaqeAIUelWjicbFViV8fIuUWfMvV3jM6sc3WsSeDrKixNZNvCJhbSefFX9MrvJvfSYHhhCidiRrjwC7mpng4oR7tOpXySOJKoj3/G+t32bDyyokQdIXCG5aoQm2KHMswEGDIQ1ZWdjfQ/bwG2lSJsFaXUECP9kl8fv7WQhpiU+DQJfjgSAOdJmoKQtWjnqfGyyNnr/X0Pn4XNjtErW6KYj7e4AvalBIV3GITHMVPeU9vg6k1wPeyN9j6b3Bn8GACmTvheMWKICwjlRP9kUk8p06eHgSeOBDKDrOLjRyo0yEf30p0cUrpplRvnMPXgd9FjTLhSbH+1dVsOo9/jbTrfmsrxW41Pdew/sWiYaeGyuEGNmlljcwdpLMgtMDCfploO2RUJND3x6lPmk6e30=
  - secure: XKwihW55kTwVRnrH1A5oP6R+qYe7tl+SFWeyw27tIDDOyVPyWbm2SgV3kQJFQ2P2kFia4E+wu3Rz4dsTSGvYAB4eFWA/msWUhPdpCE84Cwnqxpx+zkcTJ55+vxs4oau08C3Au/c7KRg6mPr08Go7X5+zZCkJ1/ff0joClRswQIfuE5Px7258xjNzk61ij+rehZnIKwisulcQvr+0O2icFyrVumg4CTdenN9h9u8ccvfCMdD6lwvtA7QV+xv7OZ9ezfx12hEUa6sQOr7XzHDbMZ32enU6TEvKpL8cq9YI2txv/B4IcTVSRwxWDVsqAgZODE9M2ZF6l1bmMTaH3Az23S8n7+SfuFRx6qhDPBOZ0M13su9oSWlUaya3gST4QvXvCZ+CHzdPHGG2rh5TW+K+QQXD52kmqyfXtkgA47aRI27c5iMuRojM4Dxm1I2r47dTYDq/0JIcIXlfqX2qd81uF0qEJ115Kmi71c64/jI7Ka6Aj2v6IXeanXvorP3lIOTIugF2oXDoPwP3+ESIfAfBbw9XhKh/uaKoTKkTKINX4R3Am2/n7/8vLw2zBGLso6X0S6Ro2DnTQ45hI3oCHbFxxAN0WT3orawuORgRjfGd5OlFNUd4Lnyy+1sZiFbe+KSlptYViUeD20lmxjwoOVzUxgtzIDSGH/da2zhINGG/GKI=
deploy:
  provider: npm
  email: zak@zeroth.io
  skip_cleanup: true
  api_key:
    secure: b+EB9MyOCxsPgjNYL2+mAXdprrCKCNeHvysK/dobtSx4NwSrlltEB2tvLisWC0b7ou+tJgmQqdyllabtQva0hmU+B7k0pTzy+/ePXlUZvYdoXYeM0eZYoEsPQublZaYtqNCpnW01U2LT3xWzNwLU2Fwu9Pi4PDiicHElK0UZEtYSc0Ghi/moJmc7fuTY74fihlJMYLb66Mdls7gu+mfcengPrZ/afCt1x3HnRhtNEVRIjR0RpX9Db/wcRnV9cxYa7c7mAtul69ZpkNnu4xusv9M38CZbdUH53NuzWwBCSF7TgKEuA33xbvmD8/FsdoX5tysL50XGqfnnquDkBfKCNnBuJNHnBi16u9bHyhhx3GsUK6ikdfyoUEf08WA4EHbwwE+Q6WMW0StsTskr4ongXofVZNVq3zjdJY2gpv6F5q7X7ZkBltNYHdevURueWPhZzJEkOUWZvy46XoyYUj4rMIwSJq+1ASiFoFwICes6U+hIT19Vw0q0vES+YqA9HXyMwNa6uSSlduzXzWYg9FTsQnHODusySsNINbGiHOv+8zUMD92ZzSdvu5p7npwHJiuguEbZ8ogfVd4R37UxsQBNdgYi8KmEOIRJ1x/ZX/GeO8P0958n/vZ2QGKCtV8iSQ+V4ukSvtunhy690SHVag58QUDK50GDJIB90IVK7jrmiBI=
  on:
    branch: master
    tags: false
