sudo: false
language: node_js
node_js:
- 5.4.1
cache:
  directories:
  - node_modules
branches:
  except:
  - "/^v[0-9\\.]+/"
before_install:
- npm install -g pr-bumper@0.3.5
- pr-bumper check
install:
- travis_retry npm install
script:
- npm test
- npm run build
after_success:
- npm run coveralls
before_deploy:
- pr-bumper bump
env:
  global:
  - secure: Wa3mTM++lxI/fMHZLLzppR0RifNWs4PyUvLOkRfpkAqiV0UA4tycXbIaJqs4Kin6ovbqsWk2vRPRyg8f2O+AUasoDLO19hp/XqXThFEMcQPsyNcHGvBpggDZN9hTER0lAaR5lKztAOxsO2ZRAhmqqLEUJ7683U8hDy5CsGUEdAQoizQylSYwndJ7jItKTzwXmukcEVOSUBbamFtcnEOxqQexgrbEhU33G659ZGJK3Wre38KdGTqeblWJF7wEI4L4SMCY9XHvCP2LSD4ng7wK2+ghf4h0x4yCw473B7nHQ1qEgnHtsZUhhw3NwCkikOHG9L8o2HL5LxSOxrTEKFMBQygfYL/h+200fcgE6nQK9lAufuyzK6XmBDpzQaORIMb+i/bkUJHWJsjMW7Qv3mFQcahs5wYTn9H9bZXAzGDFgo1mD5zZd3zbwPyJUCRe4W0L2juCeeDXRBvZmAdH1pJvunUw4OTCaikKE0z8cqnl8fIB6Kb6jcvfMCX2mBqCKkWu2kX7GR2wu6LV/6ausBiuLen6Mi/IJsO1jgF3x6ikcPPlbEuozcppNfCHlaJKB9pewtcsO/7fm3ROUzMygqVoi1QSif56TqKAzNyy42iWSSiWzt5dDUKhJwqJBVQxHxwx0zDj3wPEu65cxngLc3uC2br4wBugEkXsdSfj8p3aOLo=
  - secure: MUesrSV8Tt8qUlDEkY84E+wcr1RPnVb9Bqze6SUXBJn8SunO6R4TDctHr251scd6MIZUDUYhDzVx7nU9z+Blcua6eJdyjMPLoaH4qgo3MMnPb2q7U6v6tQQln/Llu0hUse9R7QLml0nTI5hUNunhBQwOG6eaYNzLCbe5XfESCq4szJWHNyAgVbvXG8yUpvvlGlsghRrYFDzgvDr7mVYS2ucGKAZQvEFQyaSTBO8B8g5NJ+ODg6OIwPNEvwkSAWBH0L66O4vDlRjlpSz5Fx6MtnmbGuZBd8BzfRk+9PPKFF3nRaZ1Sz5lQQIS8+QZ+VMbgjkbgDiaYVZDja4Bcb9nQ8/w3SrXOdwpAEmIL5vwtGCxTXeaYS7NnAr9YaRv71MDq+OOmwGYHm65AMBJfKzOTbyb+wmbU0EDe0gHF9P9xFshcuNdEDLbeYPQWu9o0i+HAuCkMifFz0gYPNk7DkMBPN/ucB1cFa2ASBoEVly0wiSk6YL7+IAaNZjAszfyiWI9CvptN3Wt0Z8C/sgNWkHFKn5nUrOrzM5dFT2AS3wC08gieIGRuMUiJmgIneTSU/NjgIWW8qbP/5MatD5ELLJPkWXGAEVgJ7B+0Sz3fDahvsiKz/kNZThq9nRZbHfbM/3qBpfkeLekpiVSV5lZ5RNgXvIYOpvrIyCtqVUvclegT9w=
deploy:
  provider: npm
  email: zak@ubiquits.com
  api_key:
    secure: c38j5fUA5OZCR1JMUypn24Gs4xggwiK0JrjWkWZRSsVC46jVPeS0OOWsz5ujnY7iYsjeO3aL73Coa/lujZZJNgHb56tMUUk8KpEzbmtSobRIEWiUl6M9x01GB4p65Ir+5+o8bIoo/r5yNRbr5NfPD67rPO3YgrG5KfWUN0uxE2giBdZaozouIb3MfDicF/TJFCW/GafV1vMI7YTliyw7b7f17YzKrdpqUm+M2zpRHDe0x1E/mKUDyFDcIOeCH/P5wEV8cf4ZnmKD93110wE1Ur9vPDS6kFCqTylgeaOCMP7fvWWoOe7RnQ16gecQa0dHrrdBxrSZnyJ7fByBgFXxLDbqaJ776OV9OSFagTgyyrtrw9ioCS9W6oos6Wr2KFJYC2Ib9VEDdFtMub5Jjn6+f1rw4rexnfWOlav6/ITVUptpM27BrfnXiASHIK5rzwLcmmx1l333PJgcM7mPDEyDVeb9IbeZV4f9qMVuJhdJQ7aJuPuo9H+ePi0B4zBBFr3ULeif7mYBuuqgeB/2j0If3JGzCgUWM9V7KrbOaC9TVA+0Q/VvT9aPArSKxz/30ZGG/wYuT3XkvrECRugp91Vg1XRqjPZraL8pf91RIb+2AnqZs5UKwBE8/mwSwNMrby6FQPZ5+CAEt33ujFeSOaVoaMKwnvlWAs2olwOpsafSCug=
  on:
    branch: master
    tags: false
