sudo: false
language: node_js
node_js:
- 5.4.1
addons:
  apt:
    sources:
    - libnotify-bin
cache:
  directories:
  - node_modules
branches:
  except:
  - "/^v[0-9\\.]+/"
before_install:
- npm install -g pr-bumper
- pr-bumper check
install:
- travis_retry npm install
script:
- npm test
- npm run build
before_deploy:
- pr-bumper bump
env:
  global:
    secure: dtAJfX0D+Jp27pxXPR26VnHbiZSVAYZjNcIE4fJxbwpRP+3V15VucJgEiz5ePcN5axkk4SlWVDgywaaKAupDJfvqsE8DCVmjOdqrp3aIG70xUYemMbzsqvaPRoJaONoHsKmATO2fMvTsFYvSofHgSyVpfx5PkH1zkodDWfwfSIs+FR9fEpo+ueEHj8pppB8VIX3fVDic42C1rPepx9LNVod83/LjEyZQaQIqdTW3K02p5DIJP1ESkehccFQTvG6z/ICbj+ypxZrjXo87l3UcplPZCK7eqXDmGdEUyObBoCZcyGEk6evf7x4P32zqXnL3LTXzolnH8mTqq9wZ81+dvIoPE6QL6pyi1JiSWQ6CmBTWBYyAmnyEOmTeQKOE2oWitgpwtEUITkrmolAqOKJiPsKw1TZKx+9uFmC61jlmJkeIpl7Rt3a6zS+ojNj8nBRwUXBMhEnBk+St82+UI36EoZSkOYSLeNERIy2gVMgyyVWYBgNEQYaDspIAypZ8Y0k89jCh/YlFhBJKuJznYQ/xmCpis83TDNKap1HoC0M3nTjUdtBPfsjeI5gycY3t7kxCE/q1wAdwOxYQFBzmfls+YYtKp1R0vbRPQV/StQiaPpIwNTlN+Tw8gEHV1LCaCma+qOTECcq/C+Ntc2cdhQ2xSMMHeiJbXYGsDvBiuztUlJ8=
deploy:
  provider: npm
  email: zak@ubiquits.com
  api_key:
    secure: mzxoUA4DbuxPQA3YRt760WBukYgRpcrpYk2nBT10fVLhJe6bQYxlWtdqs1EV9YhhpEeGgCmv8icvh39pdrb7xwnb9pMhMKEF+50aKKPEgY5A1hlh9KyxOiem3ksHapChqz7DAxblRQdioNudLlwFV3PxQWF0gJkjPTOwvYs+w/9xxr77IJ/FJWoTDAS/HzQMpLOGn6KUpBCMQF5XIFQdWigFCb8Ol8+Ev/lpPgvg6ehWLxt8hctEQtqX1qlX1UoYH/Jnaevs/sGY5B+o3CZUJFCE/EpYQm2dkYn0ASMb83/5inrcCPdgXmvtiVHrrBG5A72heym+E45/l0HEesvFeErLj8vsbS84anquhBGU7fFRcMEw325nRp7fX8loIIsxL1yaOYYU19Kacak3vE0kNkdR6XehifAOVtJ8X4V5ZnFcynnGW3GRC3mcAIIpTun7fpIdzSMDIQb/s9+obkIyPWzig7UzxevuPs5/PR0w+S9viUuUThMVq7Wflalt95eX4PM6nuMOZXbDcWm4bKXafBmzKy7F22Tx1pCjIFA7tfqZiju2eX3RCfRKQ3roePAFX6aVdaUC0R1QAg8G4UxGpVAWCqcZd0fc11WEeeKZVoKiUZ77axOCIKq+rH8MMnJfumSeWIFBkiopLn+X7RCWkY17gU0+RURatWIM5y+dWOM=
  on:
    tags: true
    repo: ubiquits/core
