sudo: false
language: node_js
node_js:
- 6.2.0
cache:
  directories:
  - node_modules
branches:
  except:
  - "/^v[0-9\\.]+/"
before_install:
- npm install -g pr-bumper@0.3.5
- pr-bumper check
install:
- travis_retry npm install
script:
- npm test
- npm run build
after_success:
- npm run coveralls
before_deploy:
- pr-bumper bump
env:
  global:
  - secure: VE1iK61dYazBB6VKOeEvn4i0pJs1O0fcmk/UynLCYHqa+z95IR+32uWlCTF3yfRWRJ02neEDwq8s1/7Dh/w2nfvY/7QWY9DBHXgzVCfPx+y7u4EDigC9xBa0CAz93dGlXUPDN1A/vPS87hFAzSqv52InnRXTfvqaCCTESFQrLkwdCUAq5GEaLHOFaBLcK3N6mpEQiQvpB3Hz+XLJin/o1GMzda4/jLvrS1/pj+NyHhst1NwGs25hAkcB1mT0b0sRH7c/QGofb59Vf7JKHpDRdSanJUrascywp1OM0t5HtpZqPx0g7TY7/ArrvyZzD1DCFfKsOyf7iuWzH814QM5zr1xz4vZqz9J/f1cdE1E+SeyuXUcg4hr9wTax4xB0LAzDYLG3FU+jSgL5idGrod+v9Os6QhAWvEobaEijcU2xKW4xIkBMqMrboz7SBmWn1nuudfdRM+oAQDG9ENmRQmVDYvmXJguQYeeeGU94RPTc6Y606Jr2NmiYoZ4TnTZYx37wRVgE2vVNCNuASgxWBy6bkVhs+D5FuPfi+Ucidd/Mfpiy/8DATtATbSwWz6kFW8DmmcJy1GHFTXvLVXjAI3K6V5OrCKwRh0md9GgUpMNM935I/xjsi7T0SOtZuyuxsDt1OZdeFF5MNTs92YJGfLUzh/ECjgi0XEyWevln+8mVp5o=
  - secure: Qi+UO6Dxrx75iRuBxVOPQwVWz3JACNYQr+qgpd5g3bO4ns7lbaFVKPRJWNtRY50Dl4joJgvQNDwrQhpQFbHdg2jsJhLnyNuUd3kQehHSVeP0zgayb8GAa/HxALQzTJ5YrTKsm8zbuxmmN6XQZEcX9sNIPjVTjNFhp1vNVycyJAlZicC9TCtQgJjGzQ8xt5oVDz5JRosafLb6P+AaI4UwijsdorYs5mV4GmpHiHC/FmjcosWR8xKbsldmLFxxy0YIt3j22X1xFp7LU3facakejnwrsqn1RkfE9PPXnxb+zZqPM33SXw6R1mNL+WJeCBupuhC65M2a4nND/jimKY994mY8UpoOhdcVhksdi4RSH+qiGAfWFHOzPkTdEWb9jwlNEN498loIDMSgvfrqajfJmV9jaDPciDrW5ZB2MPjBGif8v404H1I854vvDnoCbnFVyLxaz26t8pxuEg2F9gy12xmNw4W0g3ZcaYXHnFEYX9uPJxYoN5Pu4NN0whG5QYpg9Uz4MG+/pmG+2t0cFVHQgv6CrwdYQILhr5XkM3HbI59C659Li/dfdKgbZZq0opnJeFsHNzAR6NEw6qQWSR7XVJvYOm5321cU1yp7CBqkFDW5w4/O/r2PmRGjvH2uCjDbUQyGRgRKEFj+7toq4qbVJEVNnJtVcBGr96/IF3kSvVc=
deploy:
  provider: npm
  email: zak@ubiquits.com
  api_key:
    secure: c38j5fUA5OZCR1JMUypn24Gs4xggwiK0JrjWkWZRSsVC46jVPeS0OOWsz5ujnY7iYsjeO3aL73Coa/lujZZJNgHb56tMUUk8KpEzbmtSobRIEWiUl6M9x01GB4p65Ir+5+o8bIoo/r5yNRbr5NfPD67rPO3YgrG5KfWUN0uxE2giBdZaozouIb3MfDicF/TJFCW/GafV1vMI7YTliyw7b7f17YzKrdpqUm+M2zpRHDe0x1E/mKUDyFDcIOeCH/P5wEV8cf4ZnmKD93110wE1Ur9vPDS6kFCqTylgeaOCMP7fvWWoOe7RnQ16gecQa0dHrrdBxrSZnyJ7fByBgFXxLDbqaJ776OV9OSFagTgyyrtrw9ioCS9W6oos6Wr2KFJYC2Ib9VEDdFtMub5Jjn6+f1rw4rexnfWOlav6/ITVUptpM27BrfnXiASHIK5rzwLcmmx1l333PJgcM7mPDEyDVeb9IbeZV4f9qMVuJhdJQ7aJuPuo9H+ePi0B4zBBFr3ULeif7mYBuuqgeB/2j0If3JGzCgUWM9V7KrbOaC9TVA+0Q/VvT9aPArSKxz/30ZGG/wYuT3XkvrECRugp91Vg1XRqjPZraL8pf91RIb+2AnqZs5UKwBE8/mwSwNMrby6FQPZ5+CAEt33ujFeSOaVoaMKwnvlWAs2olwOpsafSCug=
  on:
    branch: master
    tags: false
